CONFIG_NAME: interop
PRESET_BASE: interop

# Genesis
GENESIS_FORK_VERSION: 0x20000089

# Time parameters
SECONDS_PER_SLOT: 2
SLOTS_PER_EPOCH: 6
EXECUTION_FOLLOW_DISTANCE: 8
EPOCHS_PER_EXECUTION_VOTING_PERIOD: 2
SECONDS_PER_EXECUTION_BLOCK: 2

# Deposit contract
DEPOSIT_CONTRACT_ADDRESS: Q4242424242424242424242424242424242424242